import crypto from 'node:crypto';
import { getDb } from '../db.js';

const MCP_URL = 'https://mcp.atlassian.com/v1/mcp';
const OAUTH = 'https://mcp.atlassian.com';
const PENDING = new Map();
const TIMEOUT_MS = 30_000;
const SAFE_TOOL = /^[a-zA-Z][a-zA-Z0-9_.-]{0,127}$/;

export class AtlassianMcpError extends Error { constructor(code) { super('Atlassian MCP unavailable'); this.code = code; } }
function fail(code) { throw new AtlassianMcpError(code); }
function encryptionKey() { const raw = process.env.ATLASSIAN_MCP_ENCRYPTION_KEY || process.env.GITHUB_OAUTH_ENCRYPTION_KEY || ''; return /^[a-f0-9]{64}$/i.test(raw) ? Buffer.from(raw, 'hex') : null; }
function seal(value) { const key = encryptionKey(); if (!key || typeof value !== 'string' || !value) fail('OAUTH_NOT_CONFIGURED'); const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', key, iv); const body = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return { ciphertext: body.toString('base64'), iv: iv.toString('base64'), tag: cipher.getAuthTag().toString('base64') }; }
function open(row, prefix) { const key = encryptionKey(); if (!key || !row?.[`${prefix}_ciphertext`]) return null; try { const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(row[`${prefix}_iv`], 'base64')); decipher.setAuthTag(Buffer.from(row[`${prefix}_tag`], 'base64')); return Buffer.concat([decipher.update(Buffer.from(row[`${prefix}_ciphertext`], 'base64')), decipher.final()]).toString('utf8'); } catch { return null; } }
function now() { return Math.floor(Date.now() / 1000); }
function audit({ event, actor = null, toolName = null, mutable = false, status = 'ok', details = {} }) { try { getDb().prepare('INSERT INTO atlassian_mcp_audits (id,event,actor,tool_name,mutable,status,details,occurred_at) VALUES (?,?,?,?,?,?,?,?)').run(`atlassian_mcp_audit_${crypto.randomUUID().replace(/-/g, '')}`, event, actor, toolName, mutable ? 1 : 0, status, JSON.stringify(details), now()); } catch { /* audit must never leak or block */ } }
function connection() { return getDb().prepare('SELECT * FROM atlassian_mcp_connection WHERE id=1').get(); }
function publicStatus() { const row = connection(); return { configured: Boolean(encryptionKey()), connected: Boolean(row), expiresAt: row?.expires_at ?? null, scopes: row?.scopes?.split(' ').filter(Boolean) ?? [], endpoint: MCP_URL }; }
export function atlassianMcpStatus() { return publicStatus(); }

async function registerClient(redirectUri) {
  const response = await fetch(`${OAUTH}/v1/register`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ client_name: 'Zero', redirect_uris: [redirectUri], grant_types: ['authorization_code', 'refresh_token'], response_types: ['code'], token_endpoint_auth_method: 'none' }) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok || typeof body.client_id !== 'string') fail('REGISTRATION_FAILED');
  return body;
}
export async function startAtlassianMcpOAuth({ redirectUri, actor }) {
  if (!encryptionKey() || typeof redirectUri !== 'string' || !redirectUri.startsWith('https://')) fail('OAUTH_NOT_CONFIGURED');
  const client = await registerClient(redirectUri); const state = crypto.randomBytes(32).toString('base64url'); const verifier = crypto.randomBytes(48).toString('base64url');
  PENDING.set(state, { verifier, client, redirectUri, expiresAt: Date.now() + 600_000, actor });
  const url = new URL(`${OAUTH}/v1/authorize`); url.searchParams.set('response_type', 'code'); url.searchParams.set('client_id', client.client_id); url.searchParams.set('redirect_uri', redirectUri); url.searchParams.set('state', state); url.searchParams.set('code_challenge', crypto.createHash('sha256').update(verifier).digest('base64url')); url.searchParams.set('code_challenge_method', 'S256');
  audit({ event: 'oauth_started', actor, status: 'pending' }); return url.toString();
}
function storeToken({ body, client }) { const access = seal(body.access_token); const refresh = typeof body.refresh_token === 'string' ? seal(body.refresh_token) : null; const clientId = seal(client.client_id); const clientSecret = typeof client.client_secret === 'string' ? seal(client.client_secret) : null; const expiresAt = Number.isFinite(Number(body.expires_in)) ? now() + Number(body.expires_in) : null; getDb().prepare(`INSERT INTO atlassian_mcp_connection (id,access_ciphertext,access_iv,access_tag,refresh_ciphertext,refresh_iv,refresh_tag,client_ciphertext,client_iv,client_tag,client_secret_ciphertext,client_secret_iv,client_secret_tag,scopes,expires_at,created_at,updated_at) VALUES (1,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET access_ciphertext=excluded.access_ciphertext,access_iv=excluded.access_iv,access_tag=excluded.access_tag,refresh_ciphertext=excluded.refresh_ciphertext,refresh_iv=excluded.refresh_iv,refresh_tag=excluded.refresh_tag,client_ciphertext=excluded.client_ciphertext,client_iv=excluded.client_iv,client_tag=excluded.client_tag,client_secret_ciphertext=excluded.client_secret_ciphertext,client_secret_iv=excluded.client_secret_iv,client_secret_tag=excluded.client_secret_tag,scopes=excluded.scopes,expires_at=excluded.expires_at,updated_at=excluded.updated_at`).run(access.ciphertext,access.iv,access.tag,refresh?.ciphertext ?? null,refresh?.iv ?? null,refresh?.tag ?? null,clientId.ciphertext,clientId.iv,clientId.tag,clientSecret?.ciphertext ?? null,clientSecret?.iv ?? null,clientSecret?.tag ?? null,typeof body.scope === 'string' ? body.scope : '',expiresAt,now(),now()); }
export async function completeAtlassianMcpOAuth({ code, state }) { const pending = PENDING.get(state); PENDING.delete(state); if (!pending || pending.expiresAt < Date.now() || typeof code !== 'string' || !code) fail('INVALID_OAUTH_CALLBACK'); const response = await fetch(`${OAUTH}/v1/token`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ grant_type: 'authorization_code', code, redirect_uri: pending.redirectUri, client_id: pending.client.client_id, code_verifier: pending.verifier }) }); const body = await response.json().catch(() => ({})); if (!response.ok || typeof body.access_token !== 'string') fail('OAUTH_EXCHANGE_FAILED'); storeToken({ body, client: pending.client }); audit({ event: 'oauth_connected', actor: pending.actor }); return publicStatus(); }
export function disconnectAtlassianMcp(actor) { const changed = getDb().prepare('DELETE FROM atlassian_mcp_connection WHERE id=1').run().changes > 0; audit({ event: 'oauth_disconnected', actor, status: changed ? 'ok' : 'noop' }); return changed; }
async function accessToken() { const row = connection(); const token = open(row, 'access'); if (!token) fail('NOT_CONNECTED'); if (!row.expires_at || row.expires_at > now() + 60) return token; const refresh = open(row, 'refresh'), clientId = open(row, 'client'), clientSecret = open(row, 'client_secret'); if (!refresh || !clientId) fail('TOKEN_EXPIRED'); const response = await fetch(`${OAUTH}/v1/token`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ grant_type: 'refresh_token', refresh_token: refresh, client_id: clientId, ...(clientSecret ? { client_secret: clientSecret } : {}) }) }); const body = await response.json().catch(() => ({})); if (!response.ok || typeof body.access_token !== 'string') fail('TOKEN_REFRESH_FAILED'); storeToken({ body: { ...body, refresh_token: body.refresh_token || refresh }, client: { client_id: clientId, ...(clientSecret ? { client_secret: clientSecret } : {}) } }); return body.access_token; }
function parseRpc(text) { const dataLine = text.split('\n').find((line) => line.startsWith('data:')); const payload = dataLine ? JSON.parse(dataLine.slice(5).trim()) : JSON.parse(text); if (payload.error) fail('MCP_RPC_ERROR'); return payload.result ?? payload; }
async function rpc({ method, params = {}, actor, toolName = null }) { const token = await accessToken(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), TIMEOUT_MS); const headers = { Authorization: `Bearer ${token}`, Accept: 'application/json, text/event-stream', 'Content-Type': 'application/json', 'MCP-Protocol-Version': '2025-03-26' }; const send = (rpcMethod, rpcParams, sessionId = null) => fetch(MCP_URL, { method: 'POST', headers: { ...headers, ...(sessionId ? { 'MCP-Session-Id': sessionId } : {}) }, body: JSON.stringify({ jsonrpc: '2.0', id: crypto.randomUUID(), method: rpcMethod, params: rpcParams }), signal: controller.signal }); try { const initialized = await send('initialize', { protocolVersion: '2025-03-26', capabilities: {}, clientInfo: { name: 'zero', version: '1.6.0' } }); if (!initialized.ok) fail('MCP_INITIALIZE_FAILED'); const sessionId = initialized.headers.get('mcp-session-id'); await initialized.text(); const response = await send(method, params, sessionId); const text = await response.text(); if (!response.ok) { audit({ event: method, actor, toolName, status: `http_${response.status}` }); fail('MCP_CALL_FAILED'); } const result = parseRpc(text); audit({ event: method, actor, toolName, status: 'ok' }); return result; } catch (error) { if (error instanceof AtlassianMcpError) throw error; audit({ event: method, actor, toolName, status: 'failed' }); fail('MCP_CALL_FAILED'); } finally { clearTimeout(timer); } }
export async function atlassianMcpCall({ toolName, arguments: args = {}, actor }) { if (!SAFE_TOOL.test(String(toolName || ''))) fail('INVALID_TOOL'); return rpc({ method: 'tools/call', params: { name: toolName, arguments: args && typeof args === 'object' && !Array.isArray(args) ? args : {} }, actor, toolName }); }
export async function atlassianMcpTools(actor) { const result = await rpc({ method: 'tools/list', actor }); return Array.isArray(result?.tools) ? result.tools.map((tool) => ({ name: String(tool?.name || ''), description: String(tool?.description || '').slice(0, 500), inputSchema: tool?.inputSchema && typeof tool.inputSchema === 'object' ? tool.inputSchema : {} })).filter((tool) => SAFE_TOOL.test(tool.name)) : []; }
