import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs';
import path from 'node:path';
import { paths } from '../config/paths.js';

const execFileAsync = promisify(execFile);
const TENANT = 'stefaniniinnovation.onmicrosoft.com';
const sessions = new Map();
function configDir() { const value = process.env.AZURE_CONFIG_DIR || path.join(paths.storageRoot, 'azure'); fs.mkdirSync(value, { recursive: true, mode: 0o700 }); return value; }
function env() { return { ...process.env, AZURE_CONFIG_DIR: configDir(), AZURE_CORE_COLLECT_TELEMETRY: 'false' }; }
function redact(value = '') { const text = String(value); return text.includes('@') ? `${text.slice(0, 2)}***${text.slice(text.indexOf('@'))}` : text.slice(0, 3) + '***'; }
export async function azureStatus() { try { await execFileAsync('az', ['version', '--output', 'json'], { timeout: 5000, env: env() }); } catch { return { installed: false, connected: false, tenant: TENANT, account: null }; } try { const { stdout } = await execFileAsync('az', ['account', 'show', '--output', 'json'], { timeout: 5000, env: env() }); const account = JSON.parse(stdout); const tenantMatches = String(account.tenantId || '').toLowerCase() === '0f220273-f596-4b58-8239-fa2c85d11a01'; return { installed: true, connected: tenantMatches, tenant: TENANT, account: tenantMatches ? { name: redact(account.user?.name), tenantId: account.tenantId } : null, error: tenantMatches ? null : 'Azure CLI is authenticated in a different tenant.' }; } catch { return { installed: true, connected: false, tenant: TENANT, account: null, error: 'Azure sign-in required.' }; } }
function publicFlow(owner) { const item = sessions.get(owner); if (!item) return { active: false }; return { active: item.active, verificationUri: item.verificationUri || 'https://microsoft.com/devicelogin', userCode: item.userCode || null, expiresAt: item.expiresAt, error: item.error || null }; }
export async function startAzureDeviceFlow(owner) { const current = await azureStatus(); if (current.connected) return { active: false, connected: true }; const prior = sessions.get(owner); if (prior?.active) return publicFlow(owner); const child = spawn('az', ['login', '--tenant', TENANT, '--use-device-code', '--only-show-errors'], { env: env(), stdio: ['ignore', 'pipe', 'pipe'] }); const item = { child, active: true, verificationUri: 'https://microsoft.com/devicelogin', userCode: null, expiresAt: Math.floor(Date.now() / 1000) + 900, error: null, output: '' }; sessions.set(owner, item); const capture = (data) => { item.output = (item.output + String(data)).slice(-8192); const url = /(https:\/\/[^\s]+)/.exec(item.output); if (url) item.verificationUri = url[1].replace(/[).,]+$/, ''); const code = /(?:code|enter)\s+([A-Z0-9]{4,}(?:-[A-Z0-9]{4,})?)/i.exec(item.output); if (code) item.userCode = code[1]; }; child.stdout.on('data', capture); child.stderr.on('data', capture); child.on('error', () => { item.active = false; item.error = 'Azure CLI failed to start.'; }); child.on('close', async (code) => { item.active = false; item.error = code === 0 && (await azureStatus()).connected ? null : (item.error || 'Azure authorization was not completed.'); }); return publicFlow(owner); }
export async function azureDeviceFlowStatus(owner) { return { ...publicFlow(owner), ...(await azureStatus()) }; }
export async function readKeyVaultSecret(vault, name) { const { stdout } = await execFileAsync('az', ['keyvault', 'secret', 'show', '--vault-name', vault, '--name', name, '--query', 'value', '--output', 'tsv', '--only-show-errors'], { timeout: 20000, maxBuffer: 128 * 1024, env: env() }); const value = stdout.trim(); if (!value) throw new Error('Key Vault returned an empty secret.'); return value; }
