import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { getDb } from '../db.js';

const execFileAsync = promisify(execFile);
const USERNAME = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const PENDING = new Map();
const OAUTH_AUTHORIZE = 'https://github.com/login/oauth/authorize';
const OAUTH_TOKEN = 'https://github.com/login/oauth/access_token';
function fail(code) { const error = new Error('GitHub credential unavailable'); error.code = code; throw error; }
function key() { const value = process.env.GITHUB_OAUTH_ENCRYPTION_KEY || ''; if (!/^[a-f0-9]{64}$/i.test(value)) return null; return Buffer.from(value, 'hex'); }
function username(value) { if (typeof value !== 'string' || !USERNAME.test(value)) fail('INVALID_OWNER'); return value; }
function encrypt(token) { const secret = key(); if (!secret) fail('OAUTH_NOT_CONFIGURED'); const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', secret, iv); const ciphertext = Buffer.concat([cipher.update(token, 'utf8'), cipher.final()]); return { ciphertext: ciphertext.toString('base64'), iv: iv.toString('base64'), tag: cipher.getAuthTag().toString('base64') }; }
function decrypt(row) { const secret = key(); if (!secret) return null; try { const decipher = crypto.createDecipheriv('aes-256-gcm', secret, Buffer.from(row.token_iv, 'base64')); decipher.setAuthTag(Buffer.from(row.token_tag, 'base64')); return Buffer.concat([decipher.update(Buffer.from(row.token_ciphertext, 'base64')), decipher.final()]).toString('utf8'); } catch { return null; } }
export function githubOAuthConfigured() { return Boolean(process.env.GITHUB_OAUTH_CLIENT_ID && process.env.GITHUB_OAUTH_CLIENT_SECRET && process.env.GITHUB_OAUTH_REDIRECT_URI && key()); }
export function createGithubOAuthAuthorization(ownerUsername) { const owner = username(ownerUsername); if (!githubOAuthConfigured()) fail('OAUTH_NOT_CONFIGURED'); const state = crypto.randomBytes(32).toString('base64url'); const verifier = crypto.randomBytes(48).toString('base64url'); const challenge = crypto.createHash('sha256').update(verifier).digest('base64url'); PENDING.set(state, { owner, verifier, expiresAt: Date.now() + 600000 }); const url = new URL(OAUTH_AUTHORIZE); url.searchParams.set('client_id', process.env.GITHUB_OAUTH_CLIENT_ID); url.searchParams.set('redirect_uri', process.env.GITHUB_OAUTH_REDIRECT_URI); url.searchParams.set('state', state); url.searchParams.set('scope', 'read:user repo'); url.searchParams.set('code_challenge', challenge); url.searchParams.set('code_challenge_method', 'S256'); return url.toString(); }
export async function completeGithubOAuthAuthorization({ code, state }) { const pending = PENDING.get(state); PENDING.delete(state); if (!pending || pending.expiresAt < Date.now() || typeof code !== 'string' || !code) fail('INVALID_OAUTH_CALLBACK'); const response = await fetch(OAUTH_TOKEN, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ client_id: process.env.GITHUB_OAUTH_CLIENT_ID, client_secret: process.env.GITHUB_OAUTH_CLIENT_SECRET, code, code_verifier: pending.verifier, redirect_uri: process.env.GITHUB_OAUTH_REDIRECT_URI }) }); const body = await response.json(); if (!response.ok || typeof body.access_token !== 'string' || !body.access_token) fail('OAUTH_EXCHANGE_FAILED'); const sealed = encrypt(body.access_token); const now = Math.floor(Date.now() / 1000); getDb().prepare(`INSERT INTO github_oauth_connections (owner_username,token_ciphertext,token_iv,token_tag,scopes,github_login,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_username) DO UPDATE SET token_ciphertext=excluded.token_ciphertext,token_iv=excluded.token_iv,token_tag=excluded.token_tag,scopes=excluded.scopes,github_login=excluded.github_login,expires_at=excluded.expires_at,updated_at=excluded.updated_at`).run(pending.owner, sealed.ciphertext, sealed.iv, sealed.tag, typeof body.scope === 'string' ? body.scope : '', null, null, now, now); return pending.owner; }
export function disconnectGithubOAuth(ownerUsername) { return getDb().prepare('DELETE FROM github_oauth_connections WHERE owner_username=?').run(username(ownerUsername)).changes > 0; }
export function githubCredentialStatus(ownerUsername) { const owner = username(ownerUsername); const row = getDb().prepare('SELECT scopes,github_login,expires_at,updated_at FROM github_oauth_connections WHERE owner_username=?').get(owner); return { oauth: row ? { connected: true, githubLogin: row.github_login, scopes: row.scopes.split(' ').filter(Boolean), expiresAt: row.expires_at, updatedAt: row.updated_at } : { connected: false }, cliAvailable: process.env.GITHUB_CLI_ENABLED === 'true', runtimeTokenAvailable: Boolean(process.env.ZERO_GREEN_GITHUB_READ_TOKEN), oauthConfigured: githubOAuthConfigured() }; }
export async function resolveGithubCredential(ownerUsername) { const owner = username(ownerUsername); const row = getDb().prepare('SELECT * FROM github_oauth_connections WHERE owner_username=?').get(owner); const oauth = row && (!row.expires_at || row.expires_at > Math.floor(Date.now() / 1000)) ? decrypt(row) : null; if (oauth) return { token: oauth, method: 'oauth' }; if (process.env.GITHUB_CLI_ENABLED === 'true') { try { const { stdout } = await execFileAsync(process.env.GITHUB_CLI_PATH || 'gh', ['auth', 'token'], { timeout: 5000, maxBuffer: 4096, env: { ...process.env, GH_CONFIG_DIR: process.env.GITHUB_CLI_CONFIG_DIR || process.env.HOME || '' } }); const token = stdout.trim(); if (token) return { token, method: 'cli' }; } catch { /* fall through */ } } const runtime = process.env.ZERO_GREEN_GITHUB_READ_TOKEN; if (runtime) return { token: runtime, method: 'runtime' }; fail('NO_CREDENTIAL'); }
