import crypto from 'node:crypto';
import { getDb } from '../db.js';
import { readKeyVaultSecret } from './azureCliService.js';

const GRAFANA_URL = 'https://grafana.saiapplications.com';
const DATASOURCE = 'P8E80F9AEF21F6940';
const MAX_RANGE_MS = 7 * 24 * 60 * 60 * 1000;
const MAX_LINES = 100;
const MAX_BYTES = 25 * 1024 * 1024 * 1024;
function now() { return Math.floor(Date.now() / 1000); }
export function validateLokiQuery({ query, start, end, limit = MAX_LINES }) { const from = Number(start); const to = Number(end); if (typeof query !== 'string' || !query.trim()) return { error: 'query is required.' }; if (!Number.isFinite(from) || !Number.isFinite(to) || to <= from) return { error: 'start and end must be epoch milliseconds with end after start.' }; if (to - from > MAX_RANGE_MS) return { error: 'Loki queries are limited to seven days.' }; if (!/\{[^}]*\bcluster\s*=\s*"[^"]+"[^}]*\}/.test(query) || !/\{[^}]*\bnamespace\s*=\s*"[^"]+"[^}]*\}/.test(query)) return { error: 'LogQL selector must pin both cluster and namespace labels.' }; if (!Number.isInteger(Number(limit)) || Number(limit) < 1 || Number(limit) > MAX_LINES) return { error: `limit must be an integer from 1 to ${MAX_LINES}.` }; return { query: query.trim(), start: from, end: to, limit: Number(limit) }; }
export async function grafanaLokiQuery({ vault = 'kv-sams-plugin', secretName = 'sams-plugin-grafana-token', query, start, end, limit, actor }) { const valid = validateLokiQuery({ query, start, end, limit }); if (valid.error) return { error: valid.error }; const token = await readKeyVaultSecret(vault, secretName); const headers = { Authorization: `Bearer ${token}`, Accept: 'application/json' }; const base = `${GRAFANA_URL}/api/datasources/proxy/uid/${DATASOURCE}/loki/api/v1`;
  // Public tool contract uses epoch milliseconds; Loki integer timestamps are nanoseconds.
  // Passing milliseconds makes Loki query January 1970 and silently return no streams.
  const startNs = `${valid.start}000000`;
  const endNs = `${valid.end}000000`;
  const stats = await fetch(`${base}/index/stats?query=${encodeURIComponent(valid.query)}&start=${startNs}&end=${endNs}`, { headers }); const statsBody = await stats.json().catch(() => ({})); const bytes = Number(statsBody?.streams ?? statsBody?.bytes ?? statsBody?.data?.bytes ?? 0); if (!stats.ok) throw new Error(`Loki cost preflight failed (${stats.status}).`); if (bytes > MAX_BYTES) return { error: 'Loki query exceeds the 25 GiB scan limit.', estimatedBytes: bytes };
  const result = await fetch(`${base}/query_range?query=${encodeURIComponent(valid.query)}&start=${startNs}&end=${endNs}&limit=${valid.limit}&direction=BACKWARD`, { headers }); const body = await result.json().catch(() => ({ error: 'Grafana returned a non-JSON response.' })); recordAudit({ actor, operation: 'query_range', status: result.status, estimatedBytes: bytes, returned: countLines(body) }); if (!result.ok) return { error: 'Loki query failed.', status: result.status }; return { status: result.status, estimatedBytes: bytes, data: truncate(body) }; }
function countLines(body) { return Array.isArray(body?.data?.result) ? body.data.result.reduce((sum, stream) => sum + (Array.isArray(stream.values) ? stream.values.length : 0), 0) : 0; }
function truncate(body) { const copy = structuredClone(body); if (Array.isArray(copy?.data?.result)) { let left = MAX_LINES; for (const stream of copy.data.result) { stream.values = Array.isArray(stream.values) ? stream.values.slice(0, Math.max(0, left)) : []; left -= stream.values.length; } copy.data.result = copy.data.result.filter((stream) => stream.values.length); } return copy; }
function recordAudit({ actor, operation, status, estimatedBytes, returned }) { try { getDb().prepare('INSERT INTO grafana_loki_audits (id,actor,operation,status,estimated_bytes,returned,occurred_at) VALUES (?,?,?,?,?,?,?)').run(`grafana_loki_${crypto.randomUUID().replace(/-/g, '')}`, actor || null, operation, status, estimatedBytes || 0, returned || 0, now()); } catch {} }
export async function grafanaLokiHealth({ vault = 'kv-sams-plugin', secretName = 'sams-plugin-grafana-token', actor }) { const token = await readKeyVaultSecret(vault, secretName); const result = await fetch(`${GRAFANA_URL}/api/datasources/uid/${DATASOURCE}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' } }); recordAudit({ actor, operation: 'datasource_health', status: result.status, estimatedBytes: 0, returned: 0 }); return { ok: result.ok, upstreamStatus: result.status }; }
export function grafanaConnectionStatus() { return { id: 'grafana-loki', label: 'Grafana / Loki', transport: 'internal-proxy', configured: true, connected: false, endpoint: GRAFANA_URL, capabilities: ['loki-read'], authentication: 'Azure Key Vault service account token', vault: 'kv-sams-plugin', secretName: 'sams-plugin-grafana-token' }; }
