import crypto from 'node:crypto';
import { getDb } from '../db.js';
import { getPluginAccessGrant } from './pluginAccessStore.js';
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const PATH = /^references\/[A-Za-z0-9][A-Za-z0-9._/-]*\.md$/;
function fail(message) { throw new Error(`Invalid plugin skill reference request: ${message}`); }
function id(value, field) { if (typeof value !== 'string' || !ID.test(value)) fail(`${field} must be a safe identifier`); return value; }
function scope(input) { const hasVersion = input.versionId != null; const hasCommit = input.sourceCommit != null; if (hasVersion === hasCommit) fail('requires exactly one of versionId or sourceCommit'); return hasVersion ? { versionId: id(input.versionId, 'versionId') } : { sourceCommit: id(input.sourceCommit, 'sourceCommit') }; }
function resolve(input) { const s = scope(input); const sql = s.versionId ? `SELECT p.package_key,p.status package_status,v.id,v.source_commit,v.status version_status,v.manifest FROM prompt_packages p JOIN prompt_package_versions v ON v.package_id=p.id WHERE p.package_key=? AND v.id=?` : `SELECT p.package_key,p.status package_status,v.id,v.source_commit,v.status version_status,v.manifest FROM prompt_packages p JOIN prompt_package_versions v ON v.package_id=p.id WHERE p.package_key=? AND v.source_commit=?`; return getDb().prepare(sql).get(input.packageKey, s.versionId || s.sourceCommit); }
function skillPath(manifestText, key) { try { const manifest = JSON.parse(manifestText); const matches = (manifest.skills || []).filter((skill) => skill?.key === key); return matches.length === 1 ? matches[0].path : null; } catch { return null; } }
export function readPluginSkillReference(input) { if (!input || typeof input !== 'object' || Array.isArray(input)) fail('input must be an object'); for (const key of Object.keys(input)) if (!['username','agentId','packageKey','versionId','sourceCommit','skill','path','sessionId','executionId'].includes(key)) fail(`${key} is not supported`); const username=id(input.username,'username'),agentId=id(input.agentId,'agentId'),packageKey=id(input.packageKey,'packageKey'),skill=id(input.skill,'skill'); if (typeof input.path !== 'string' || !PATH.test(input.path) || input.path.includes('..')) fail('path must be an allowed relative Markdown reference'); const version=resolve({packageKey,versionId:input.versionId,sourceCommit:input.sourceCommit}); if (!version || !['active','staged'].includes(version.package_status) || !['active','staged'].includes(version.version_status)) return { outcome:'unavailable' }; const grant=getPluginAccessGrant({username,agentId,scope:{packageKey,versionId:version.id}}); if (!grant || grant.mode !== 'direct' || grant.exclusions.skills.includes(skill) || !grant.approvedFeatures.skills.includes(skill)) return { outcome:'unavailable' }; const source=skillPath(version.manifest,skill); if (!source) return { outcome:'unavailable' }; const root=source === 'SKILL.md' ? '' : source.slice(0,-'/SKILL.md'.length); const expected=`${root ? `${root}/` : ''}${input.path}`; const artifact=getDb().prepare(`SELECT a.source_path,a.content_hash,a.prompt_block_id,a.prompt_block_version_id,b.content FROM prompt_package_artifacts a JOIN prompt_block_versions b ON b.id=a.prompt_block_version_id AND b.block_id=a.prompt_block_id WHERE a.package_version_id=? AND a.type='reference' AND a.source_path=?`).get(version.id,expected); if (!artifact || crypto.createHash('sha256').update(artifact.content,'utf8').digest('hex') !== artifact.content_hash) return { outcome:'unavailable' }; const details={agentId,featureKey:skill,action:'reference_read'}; if (input.sessionId) details.sessionId=id(input.sessionId,'sessionId'); if (input.executionId) details.executionId=id(input.executionId,'executionId'); const eventId=`plugin_access_event_${crypto.randomUUID().replace(/-/g,'')}`; getDb().prepare('INSERT INTO plugin_access_events (id,owner_username,package_version_id,event,actor,details,created_at) VALUES (?,?,?,?,?,?,unixepoch())').run(eventId,username,version.id,'plugin_skill_reference_read',username,JSON.stringify(details)); const label=`UNTRUSTED_PLUGIN_SKILL_REFERENCE package=${packageKey} versionId=${version.id} sourceCommit=${version.source_commit} skill=${skill} path=${input.path} contentHash=${artifact.content_hash}`; return { outcome:'direct', reference:{ path:input.path, contentHash:artifact.content_hash, content:`<<<${label}>>>\n${artifact.content}\n<<<END_UNTRUSTED_PLUGIN_SKILL_REFERENCE>>>` } }; }
