import React from 'react';
import { disconnectAtlassianMcp, getAtlassianMcpStatus, listAtlassianMcpTools, startAtlassianMcpOAuth, type AtlassianMcpConnectionStatus } from '../services/localApiService';

export default function AtlassianMcpSettings() {
  const [status, setStatus] = React.useState<AtlassianMcpConnectionStatus | null>(null);
  const [tools, setTools] = React.useState<Array<{ name: string; description: string }>>([]);
  const [busy, setBusy] = React.useState(''); const [error, setError] = React.useState('');
  const refresh = React.useCallback(async () => { setError(''); try { const next = await getAtlassianMcpStatus(); setStatus(next); if (next.connected) { const result = await listAtlassianMcpTools(); setTools(Array.isArray(result.tools) ? result.tools : []); } else setTools([]); } catch (e: any) { setError(e?.message || 'Unable to load Atlassian MCP status.'); } }, []);
  React.useEffect(() => { void refresh(); }, [refresh]);
  const connect = async () => { setBusy('connect'); setError(''); try { const result = await startAtlassianMcpOAuth(); window.location.assign(result.authorizationUrl); } catch (e: any) { setError(e?.message || 'Unable to start Atlassian authorization.'); setBusy(''); } };
  const disconnect = async () => { if (!window.confirm('Disconnect the global Atlassian MCP connection?')) return; setBusy('disconnect'); try { await disconnectAtlassianMcp(); await refresh(); } catch (e: any) { setError(e?.message || 'Unable to disconnect Atlassian MCP.'); } finally { setBusy(''); } };
  return <section className="max-w-3xl space-y-4"><div><h3 className="text-sm font-black uppercase tracking-widest text-slate-700 dark:text-slate-200">Atlassian MCP</h3><p className="mt-1 text-xs text-slate-500">Global OAuth connection for the official Atlassian MCP. Authorized agents may use Jira and Confluence tools; write operations require confirmation when invoked.</p></div><div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-3"><div><b className="text-sm">{status?.connected ? 'Connected' : 'Not connected'}</b><p className="text-xs text-slate-500">{status?.connected ? `Endpoint: ${status.endpoint}` : status?.configured ? 'Connect to discover available tools.' : 'Server encryption is not configured.'}</p>{status?.expiresAt ? <p className="text-xs text-slate-500">Token expires: {new Date(status.expiresAt * 1000).toLocaleString()}</p> : null}</div><div className="flex gap-2"><button onClick={() => void refresh()} disabled={!!busy} className="rounded border border-slate-300 px-3 py-1.5 text-xs font-bold dark:border-slate-600">Refresh</button>{status?.connected ? <button onClick={() => void disconnect()} disabled={!!busy} className="rounded bg-red-600 px-3 py-1.5 text-xs font-bold text-white">{busy === 'disconnect' ? 'Disconnecting…' : 'Disconnect'}</button> : <button onClick={() => void connect()} disabled={!!busy || !status?.configured} className="rounded bg-indigo-600 px-3 py-1.5 text-xs font-bold text-white">{busy === 'connect' ? 'Opening…' : 'Connect Atlassian'}</button>}</div></div>{status?.scopes?.length ? <p className="mt-3 text-xs text-slate-500">Scopes: {status.scopes.join(', ')}</p> : null}</div>{error ? <p className="rounded border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300">{error}</p> : null}{status?.connected && <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h4 className="text-xs font-black uppercase tracking-widest text-slate-500">Discovered tools</h4>{tools.length ? <ul className="mt-3 space-y-2">{tools.map(tool => <li key={tool.name} className="rounded border border-slate-100 p-2 text-xs dark:border-slate-800"><b>{tool.name}</b>{tool.description ? <p className="mt-1 text-slate-500">{tool.description}</p> : null}</li>)}</ul> : <p className="mt-3 text-xs text-slate-500">No tools returned yet. Refresh to retry discovery.</p>}</div>}</section>;
}
