import { NODE_META } from './NodeIcon';
import NodeIcon from './NodeIcon';

const IC  = "w-full bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-800 dark:text-slate-200 font-mono focus:outline-none focus:border-slate-400 dark:focus:border-slate-500 transition-colors placeholder-slate-400 dark:placeholder-slate-600";
const LC  = "block text-[10px] font-bold text-slate-500 dark:text-slate-500 uppercase tracking-widest mb-1.5";
const TA  = `${IC} resize-none leading-relaxed`;

const NodeCard = ({ node, idx, total, agents, models, workflows, expanded, onToggle, onMove, onRemove, onLabel, onCfg }: any) => {
  const m = NODE_META[node.type] || NODE_META.trigger;
  const upd = (k: string, v: any) => onCfg(k, v);
  const cfg = node.config;

  const renderConfig = () => {
    switch (node.type) {
      case 'llm': return (
        <div className="space-y-3">
          <div><label className={LC}>Model</label><select value={cfg.modelId || ''} onChange={e => upd('modelId', e.target.value)} className={IC}><option value="">— inherit from agent —</option>{models.map((m: any) => <option key={m.id} value={m.modelId}>{m.name}</option>)}</select></div>
          <div><label className={LC}>Prompt</label><textarea value={cfg.prompt || ''} onChange={e => upd('prompt', e.target.value)} rows={4} className={TA} placeholder="Instruction... Use {{prev}} for previous output." /></div>
          <div className="grid grid-cols-2 gap-2"><div><label className={LC}>Temperature</label><input type="number" min={0} max={2} step={0.1} value={cfg.temperature ?? ''} onChange={e => upd('temperature', parseFloat(e.target.value))} className={IC} placeholder="0.7" /></div><div><label className={LC}>Max tokens</label><input type="number" value={cfg.maxTokens ?? ''} onChange={e => upd('maxTokens', parseInt(e.target.value))} className={IC} placeholder="1000" /></div></div>
        </div>
      );
      case 'agent': return (
        <div className="space-y-3">
          <div><label className={LC}>Task / Instruction</label><textarea value={cfg.task || ''} onChange={e => upd('task', e.target.value)} rows={4} className={TA} placeholder={"Analyze recent memories and identify any outdated entries."} /><p className="text-[10px] text-slate-600 mt-1">The agent runs with its full system prompt, tools and memory context.</p></div>
          <div><label className={LC}>Agent</label><div className="flex gap-2 mb-2"><button onClick={() => upd('useContextAgent', true)} className={`flex-1 py-1.5 rounded text-[11px] font-bold transition-colors border ${cfg.useContextAgent !== false ? 'bg-nebula-500/15 text-nebula-400 border-nebula-500/30' : 'bg-slate-800 text-slate-500 border-slate-700 hover:text-slate-300'}`}>Pipeline agent</button><button onClick={() => upd('useContextAgent', false)} className={`flex-1 py-1.5 rounded text-[11px] font-bold transition-colors border ${cfg.useContextAgent === false ? 'bg-nebula-500/15 text-nebula-400 border-nebula-500/30' : 'bg-slate-800 text-slate-500 border-slate-700 hover:text-slate-300'}`}>Specific agent</button></div>{cfg.useContextAgent === false && (<select value={cfg.agentId || ''} onChange={e => upd('agentId', e.target.value)} className={IC}><option value="">— select agent —</option>{agents.map((a: any) => <option key={a.id} value={a.id}>{a.name}</option>)}</select>)}</div>
          <div><label className={LC}>Previous output variable</label><input value={cfg.outputVar || ''} onChange={e => upd('outputVar', e.target.value)} className={IC} placeholder="{{prev}} available by default" /></div>
          <div className="grid grid-cols-3 gap-2"><div><label className={LC}>Timeout (s)</label><input type="number" min={10} max={3600} value={cfg.timeoutSeconds ?? 300} onChange={e => upd('timeoutSeconds', parseInt(e.target.value))} className={IC} /><p className="text-[9px] text-slate-700 mt-1">Default 300s</p></div><div><label className={LC}>Max retries</label><input type="number" min={1} max={10} value={cfg.maxRetries ?? 3} onChange={e => upd('maxRetries', parseInt(e.target.value))} className={IC} /></div><div><label className={LC}>Retry delay (s)</label><input type="number" min={1} max={60} value={cfg.retryDelaySeconds ?? 10} onChange={e => upd('retryDelaySeconds', parseInt(e.target.value))} className={IC} /></div></div>
        </div>
      );
      case 'http': return (<div className="space-y-3"><div className="flex gap-2"><div className="w-24 shrink-0"><label className={LC}>Method</label><select value={cfg.method || 'GET'} onChange={e => upd('method', e.target.value)} className={IC}>{['GET','POST','PUT','DELETE','PATCH'].map(m => <option key={m}>{m}</option>)}</select></div><div className="flex-1 min-w-0"><label className={LC}>URL</label><input value={cfg.url || ''} onChange={e => upd('url', e.target.value)} className={IC} placeholder="https://api.example.com/endpoint" /></div></div><div><label className={LC}>Headers (JSON)</label><textarea value={typeof cfg.headers === 'object' ? JSON.stringify(cfg.headers, null, 2) : (cfg.headers || '')} onChange={e => { try { upd('headers', JSON.parse(e.target.value)); } catch { upd('headers', e.target.value); }}} rows={2} className={TA} placeholder='{"Authorization": "Bearer {{MY_TOKEN}}"}' /></div><div><label className={LC}>Body</label><textarea value={cfg.body || ''} onChange={e => upd('body', e.target.value)} rows={3} className={TA} placeholder='{"key": "{{value}}"}' /></div></div>);
      case 'condition': return (<div className="space-y-3"><div><label className={LC}>Expression</label><input value={cfg.expression || ''} onChange={e => upd('expression', e.target.value)} className={IC} placeholder="{{output}}.includes('success')" /><p className="text-[10px] text-slate-600 mt-1">Must evaluate to true/false.</p></div><div className="grid grid-cols-2 gap-2"><div><label className={LC}>True label</label><input value={cfg.trueLabel || 'Yes'} onChange={e => upd('trueLabel', e.target.value)} className={IC} /></div><div><label className={LC}>False label</label><input value={cfg.falseLabel || 'No'} onChange={e => upd('falseLabel', e.target.value)} className={IC} /></div></div></div>);
      case 'loop': return (<div className="space-y-3"><div><label className={LC}>Items expression</label><input value={cfg.items || ''} onChange={e => upd('items', e.target.value)} className={IC} placeholder="{{output}}.split('\n')" /><p className="text-[10px] text-slate-600 mt-1">Expression resolving to an array.</p></div><div><label className={LC}>Loop variable</label><input value={cfg.variable || 'item'} onChange={e => upd('variable', e.target.value)} className={IC} placeholder="item" /></div><div><label className={LC}>Max iterations</label><input type="number" value={cfg.maxIterations || 100} onChange={e => upd('maxIterations', parseInt(e.target.value))} className={IC} /></div></div>);
      case 'code': return (<div className="space-y-3"><div><label className={LC}>Language</label><div className="flex gap-2">{(['javascript','python'] as const).map(lang => (<button key={lang} onClick={() => upd('language', lang)} className={`flex-1 py-1.5 rounded text-[11px] font-bold uppercase tracking-wider transition-colors ${cfg.language === lang ? 'bg-pink-500/20 text-pink-300 border border-pink-500/30' : 'bg-slate-800 text-slate-500 border border-slate-700 hover:text-slate-300'}`}>{lang === 'javascript' ? 'JS' : 'Python'}</button>))}</div></div><div><label className={LC}>Code</label><textarea value={cfg.code || ''} onChange={e => upd('code', e.target.value)} rows={6} className={`${TA} text-[11px]`} placeholder={cfg.language === 'python' ? '# return input["prev"].upper()' : '// return input.prev.trim()'} /></div></div>);
      case 'subworkflow': return (<div className="space-y-3"><div><label className={LC}>Pipeline</label><select value={cfg.workflowId || ''} onChange={e => upd('workflowId', e.target.value)} className={IC}><option value="">— select pipeline —</option>{workflows.map((w: any) => <option key={w.id} value={w.id}>{w.name}</option>)}</select></div><div><label className={LC}>Input mapping (JSON)</label><textarea value={cfg.inputMapping || ''} onChange={e => upd('inputMapping', e.target.value)} rows={3} className={TA} placeholder='{"input": "{{output}}"}' /></div></div>);
      case 'transform': return (<div className="space-y-3"><div><label className={LC}>Expression</label><input value={cfg.expression || ''} onChange={e => upd('expression', e.target.value)} className={IC} placeholder="{{output}}.trim().toUpperCase()" /></div><div><label className={LC}>Output variable</label><input value={cfg.outputVariable || 'result'} onChange={e => upd('outputVariable', e.target.value)} className={IC} placeholder="result" /></div></div>);
      case 'delay': return (<div className="space-y-2"><label className={LC}>Duration (ms)</label><input type="number" value={cfg.duration || 1000} onChange={e => upd('duration', parseInt(e.target.value))} className={IC} /></div>);
      case 'alert': return (<div className="space-y-3"><div><label className={LC}>Level</label><div className="flex gap-1.5">{(['info','warning','error','success'] as const).map(lvl => { const lc: Record<string,string> = { info: 'text-sky-400 border-sky-500/30 bg-sky-500/10', warning: 'text-amber-400 border-amber-500/30 bg-amber-500/10', error: 'text-red-400 border-red-500/30 bg-red-500/10', success: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10' }; return <button key={lvl} onClick={() => upd('level', lvl)} className={`flex-1 py-1 rounded text-[10px] font-bold uppercase tracking-wider border transition-colors ${cfg.level === lvl ? lc[lvl] : 'bg-slate-800 text-slate-600 border-slate-700'}`}>{lvl}</button>; })}</div></div><div><label className={LC}>Message</label><textarea value={cfg.message || ''} onChange={e => upd('message', e.target.value)} rows={2} className={TA} placeholder="Pipeline completed: {{output}}" /></div></div>);
      default: return null;
    }
  };

  return (
    <div className={`relative rounded-xl border transition-all duration-150 ${expanded ? `${m.border} bg-white dark:bg-slate-900` : 'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/60 hover:border-slate-300 dark:hover:border-slate-700'}`}>
      <div className="flex items-center gap-3 px-4 py-3 cursor-pointer select-none" onClick={onToggle}>
        <div className="w-5 h-5 rounded-full bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 flex items-center justify-center shrink-0"><span className="text-[9px] font-black text-slate-500">{idx + 1}</span></div>
        <div className={`flex items-center gap-1.5 px-2 py-1 rounded-md border ${m.bg} ${m.border} shrink-0`}><span className={m.color}><NodeIcon type={node.type} sz={3} /></span><span className={`text-[10px] font-black uppercase tracking-wider ${m.color}`}>{m.label}</span></div>
        <input value={node.label} onChange={e => { e.stopPropagation(); onLabel(e.target.value); }} onClick={e => e.stopPropagation()} className="flex-1 bg-transparent text-sm font-semibold text-slate-700 dark:text-slate-300 outline-none border-b border-transparent hover:border-slate-300 dark:hover:border-slate-700 focus:border-slate-400 dark:focus:border-slate-500 transition-colors min-w-0" placeholder="Step label..." />
        <div className="flex items-center gap-0.5 shrink-0" onClick={e => e.stopPropagation()}>
          <button onClick={() => onMove('up')} disabled={idx === 0} className="p-1 rounded text-slate-600 hover:text-slate-300 disabled:opacity-20 transition-colors">↑</button>
          <button onClick={() => onMove('down')} disabled={idx === total - 1} className="p-1 rounded text-slate-600 hover:text-slate-300 disabled:opacity-20 transition-colors">↓</button>
          <button onClick={onRemove} className="p-1 rounded text-slate-600 hover:text-red-400 transition-colors">✕</button>
        </div>
      </div>
      {expanded && <div className="px-4 pb-4 border-t border-slate-200 dark:border-slate-800 pt-3"><p className="text-[10px] text-slate-600 mb-3">{m.description}</p>{renderConfig()}</div>}
    </div>
  );
};

export default NodeCard;
